---
keycloak:
  ingress:
    enabled: true
    hosts:
      - keycloak.192.168.26.11.nip.io
    annotations:
      kubernetes.io/ingress.class: nginx
    tls:
      - secretName: keycloak-tls
        hosts:
          - keycloak.192.168.26.11.nip.io

  persistence:
    deployPostgres: true
    dbVendor: postgres
    dbPassword: changeme

postgresql:
  postgresPassword: changeme
